name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  continuous-integration:
    uses: ./.github/workflows/continuous-integration.yml
    name: continuous integration

  Docker_Hub:
    name: Docker Hub
    concurrency:
      group: ${{ github.event.repository.name }}-deploy-Docker_Hub
    needs: continuous-integration
    uses: hypothesis/workflows/.github/workflows/dockerhub.yml@main
    with:
      Application: ${{ github.event.repository.name }}
    secrets: inherit

  QA:
    concurrency:
      group: ${{ github.event.repository.name }}-deploy-qa
    needs: Docker_Hub
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: QA
      aws_region: us-west-1
      elasticbeanstalk_application: dummy-h-periodic
      elasticbeanstalk_environment: qa
      docker_tag: ${{ needs.Docker_Hub.outputs.docker_tag }}
    secrets: inherit

  Production:
    concurrency:
      group: ${{ github.event.repository.name }}-deploy-us
      cancel-in-progress: true
    needs: [Docker_Hub, QA]
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: Production
      aws_region: us-west-1
      elasticbeanstalk_application: dummy-h-periodic
      elasticbeanstalk_environment: prod
      docker_tag: ${{ needs.Docker_Hub.outputs.docker_tag }}
    secrets: inherit

  Production_Canada:
    concurrency:
      group: ${{ github.event.repository.name }}-deploy-ca
      cancel-in-progress: true
    needs: [Docker_Hub, QA]
    name: Production (Canada)
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: Production (Canada)
      aws_region: ca-central-1
      elasticbeanstalk_application: dummy-h-periodic
      elasticbeanstalk_environment: prod
      docker_tag: ${{ needs.Docker_Hub.outputs.docker_tag }}
    secrets: inherit
