# Builds and pushes a callers docker container to docker hub
name: dockerhub.yml

on:
  workflow_call:
    inputs:
      Application:
        type: string
        required: true
        description: "The name of the application that wants to create a container."
    secrets:
      DEPLOYMENT_DOCKER_USER:
        required: true
      DEPLOYMENT_DOCKER_USER_KEY:
        required: true

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    env:
      name: ${{ inputs.Application }}
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          echo "Name is $APP"
          GIT_SHORT=$(git rev-parse --short HEAD)
          GIT_COMMIT_TIMESTAMP=$(git --no-pager show -s --format=%ct $GIT_SHORT)
          GIT_TS_CONVERTED=$(date -d @$GIT_COMMIT_TIMESTAMP +"%Y%m%d")
          VERSION=$(echo "$GIT_TS_CONVERTED-g$GIT_SHORT")
          export TAG=${VERSION//+/-}
          echo "::set-env name=TAG::$TAG"
          git archive HEAD | docker build -t "hypothesis/${name}:${TAG}" -
      - name: push
        run: |
          echo "${{ secrets.DEPLOYMENT_DOCKER_USER_KEY }}" | docker login -u "${{ secrets.DEPLOYMENT_DOCKER_USER }}"  --password-stdin
          docker push "hypothesis/${name}:${TAG}"
          docker tag "hypothesis/${name}:${TAG}" "hypothesis/${name}:latest"
          docker push "hypothesis/${name}:latest"
