name: EB Caller

on:
  workflow_dispatch:
    inputs: 
      Application:
        type: choice
        description: "The application to be updated."
        options:
          - dummy-h-periodic
        required: true
      Operation:
        type: choice
        description: "Choose the deployment operation. `redeploy` triggers a redeployment of the currently-deployed version. `deploy` releases and deploys a specific application version. `sync-env` synchronizes the environment definition."
        required: true
        default: 'redeploy'
        options:
          - redeploy
          - deploy
          - sync-env
      Version:
        description: "The tag of the application docker image to deploy. This is required if the selected deployment type is `deploy`."
      Environment:
        type: choice
        description: "The environment to deploy. Can be either: 'qa' or 'prod'."
        required: true
        default: 'qa'
        options:
          - qa
          - prod
      Region:
        type: choice
        description: "The AWS region to target. Can be either: 'us-west-1', or 'ca-central-1', or 'all'."
        required: true
        default: 'all'
        options:
          - us-west-1
          - ca-central-1
          - all
jobs:
  eb-update:
    uses: ./.github/workflows/eb-reuse.yml
    with:
      Application: ${{ github.event.inputs.Application }}
      Operation: ${{ github.event.inputs.Operation }}
      Environment: ${{ github.event.inputs.Environment }}
      Region: ${{ github.event.inputs.Region }}
      Version: ${{ github.event.inputs.Version }}
    secrets: inherit
