name: looper

on:
  workflow_dispatch:
    inputs:
      Region:
        type: choice
        description: "The AWS region to target"
        required: true
        default: 'all'
        options:
          - 'all'
          - 'us-west-1'
          - 'ca-central-1'

jobs:
  all_regions:
    if: inputs.Region == 'all'
    strategy:
      matrix:
        regions: [us-west-1, ca-central-1]
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ matrix.regions }}"
  us_region:
    if: inputs.Region == 'us-west-1'
    strategy:
      matrix:
        regions: [us-west-1]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ matrix.regions }}"
  ca_region:
    if: inputs.Region == 'ca-central-1'
    strategy:
      matrix:
        regions: [ca-central-1]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ matrix.regions }}"
