name: prod-release

concurrency:
  group: ${{ github.event.repository.name }}-release
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  prod:
    name: ${{ github.event.repository.name }}
    uses: hypothesis/workflows/.github/workflows/eb-update.yml@main
    with:
      Application: ${{ github.event.repository.name }}
      Environment: prod
      Region: us-west-1
      Operation: deploy
      Version: latest
    secrets: inherit
