name: Redeploy
concurrency:
  group: deploy
  cancel-in-progress: true
on:
  workflow_dispatch:
    inputs:
      qa:
        type: boolean
        description: Redeploy QA
      Production:
        type: boolean
        description: Redeploy Production
      production_canada:
        type: boolean
        description: Redeploy Production (Canada)
jobs:
  qa:
    name: QA
    if: inputs.qa
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: QA
      aws_region: us-west-1
      elasticbeanstalk_application: dummy-h-periodic
      elasticbeanstalk_environment: qa
    secrets: inherit
  Production:
    name: Production
    if: inputs.Production
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: Production
      aws_region: us-west-1
      elasticbeanstalk_application: dummy-h-periodic
      elasticbeanstalk_environment: prod
    secrets: inherit
  production_canada:
    name: Production (Canada)
    if: inputs.production_canada
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: Production (Canada)
      aws_region: ca-central-1
      elasticbeanstalk_application: dummy-h-periodic
      elasticbeanstalk_environment: prod
    secrets: inherit
