name: Release

on:
  push:

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    env:
      name: dummy-h-periodic
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        echo "All branches - Build"
        GIT_SHORT=$(git rev-parse --short HEAD)
        GIT_COMMIT_TIMESTAMP=$(git --no-pager show -s --format=%ct $GIT_SHORT)
        GIT_TS_CONVERTED=$(date -d @$GIT_COMMIT_TIMESTAMP +"%Y%m%d")
        VERSION=$(echo "$GIT_TS_CONVERTED-g$GIT_SHORT")
        TAG=${VERSION//+/-}
        git archive HEAD | docker build -t ${name}:${TAG} -
        docker image ls
    - name: Test
      run: |
        docker image ls
    - name: Release
      run: |
        BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
        if [ $BRANCH_NAME = 'master' ] ; then echo "Master branch - Release" ; fi

  deploy-qa:
    name: Deploy QA
    needs: build-and-release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Dummy Deploy QA
      run: echo "Master branch - Deploy QA"

  deploy-prod:
    name: Deploy Prod
    needs: deploy-qa
    runs-on: ubuntu-latest
    environment: Approval
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Dummy Deploy Prod
      run: echo "Master branch - Deploy prod"
