name: Release

on:
  push:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Dummy step
      run: echo "Build and Release"

  deploy-qa:
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
    - name: Dummy step
      run: echo "Deploy QA"

  approval:
    needs: deploy-qa
    runs-on: ubuntu-latest
    steps:
    - name: Dummy step
      run: echo "Approval"

  deploy-prod:
    needs: approval
    runs-on: ubuntu-latest
    steps:
    - name: Dummy step
      run: echo "Deploy prod"
