name: Release

concurrency:
  group: ${{ github.event.repository.name }}-release
  cancel-in-progress: true

on:
  push:
    branches:
      - main

env:
  APPLICATION: ${{ github.event.repository.name }}
  OPERATION: deploy
  VERSION: latest

jobs:
  continuous-integration:
    uses: ./.github/workflows/continuous-integration.yml
    name: continuous integration

  create-image:
    needs: continuous-integration
    uses: hypothesis/workflows/.github/workflows/dockerhub.yml@main
    with:
      Application: $APPLICATION
    secrets: inherit

  qa-us-west-1:
    needs: create-image
    name: ${{ github.event.repository.name }}
    uses: hypothesis/workflows/.github/workflows/eb-update.yml@main
    with:
      Application: $APPLICATION
      Operation: $OPERATION
      Version: $VERSION
      Environment: qa
      Region: us-west-1
    secrets: inherit

  prod-us-west-1:
    needs: qa-us-west-1
    name: ${{ github.event.repository.name }}
    uses: hypothesis/workflows/.github/workflows/eb-update.yml@main
    with:
      Application: $APPLICATION
      Operation: $OPERATION
      Version: $VERSION
      Environment: prod
      Region: us-west-1
    secrets: inherit

  prod-ca-central-1:
    needs: qa-us-west-1
    name: ${{ github.event.repository.name }}
    uses: hypothesis/workflows/.github/workflows/eb-update.yml@main
    with:
      Application: $APPLICATION
      Operation: $OPERATION
      Version: $VERSION
      Environment: prod
      Region: ca-central-1
    secrets: inherit
