name: Release

on:
  push:

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dummy Build
      run: echo "All branches - Build and Release"
    - name: Dummy Release
      run: |
        BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
        if [ $BRANCH_NAME = 'master' ] ; then echo "Master branch - Release" ; fi

  deploy-qa:
    name: Deploy QA
    needs: build-and-release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Dummy Deploy QA
      run: echo "Master branch - Deploy QA"

  approval:
    name: Approval
    needs: deploy-qa
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Dummy Approval Stage
      run: echo "Master branch - Approval"

  deploy-prod:
    name: Deploy Prod
    needs: approval
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Dummy Deploy Prod
      run: echo "Master branch - Deploy prod"
