name: Release

on:
  push:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Dummy build
      run: echo "Build"
    - name: Dummy release
      run: echo "release"

  deploy-qa:
    if: github.ref == 'refs/heads/master'
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
    - name: Dummy step
      run: echo "Master branch: Deploy QA"

  approval:
    if: github.ref == 'refs/heads/master'
    needs: deploy-qa
    runs-on: ubuntu-latest
    steps:
    - name: Dummy step
      run: echo "Mater branch: Approval"

  deploy-prod:
    if: github.ref == 'refs/heads/master'
    needs: approval
    runs-on: ubuntu-latest
    steps:
    - name: Dummy step
      run: echo "Master branch: Deploy prod"
