name: Automated Release

concurrency: dummy-h-periodic-release

on:
  push:

permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  AWS_SESSION_TOKEN: $ACTIONS_ID_TOKEN_REQUEST_TOKEN
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  APP: 'dummy-h-periodic'
  TYPE: 'deploy'
  US_REGION: 'us-west-1'
  CA_REGION: 'ca-central-1'

jobs:
  build-test-push:
    name: Build, Test & Push
    runs-on: ubuntu-latest
    env:
      name: dummy-h-periodic
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        GIT_SHORT=$(git rev-parse --short HEAD)
        GIT_COMMIT_TIMESTAMP=$(git --no-pager show -s --format=%ct $GIT_SHORT)
        GIT_TS_CONVERTED=$(date -d @$GIT_COMMIT_TIMESTAMP +"%Y%m%d")
        VERSION=$(echo "$GIT_TS_CONVERTED-g$GIT_SHORT")
        export TAG=${VERSION//+/-}
        echo "::set-env name=TAG::$TAG"
        git archive HEAD | docker build -t "hypothesis/${name}:${TAG}" -
    - name: Test
      run: |
        echo "Add tests here!"
    - name: Push
      if: github.ref == 'refs/heads/main'
      run: |
        echo "${{ secrets.DOCKER_KEY }}" | docker login -u indigobravo  --password-stdin
        docker push "hypothesis/${name}:${TAG}"
        docker tag "hypothesis/${name}:${TAG}" "hypothesis/${name}:latest"
        docker push "hypothesis/${name}:latest"

  deploy-qa:
    name: QA - US-West-1
    needs: build-test-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::964867326460:role/Deployments
        role-duration-seconds: 900
        aws-region: us-west-1
    - name: Checkout deployment repo
      uses: actions/checkout@v3
      with:
        repository: hypothesis/dummy-deploy
        ssh-key: ${{ secrets.DEPLOYMENT_KEY }}
    - name: install boto3
      run: pip install boto3
    - name: Run QA Deployment
      run: |
        export APP="dummy-h-periodic" TYPE="deploy" ENV="qa" REGION="us-west-1" APP_DOCKER_VERSION="latest"
        ./bin/jenkins

  deploy-prod-us-west-1:
    name: Prod - US-West-1
    needs: deploy-qa
    runs-on: ubuntu-latest
    environment: Production
    if: github.ref == 'refs/heads/main'
    steps:
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::964867326460:role/Deployments
        role-duration-seconds: 900
        aws-region: us-west-1
    - name: Checkout deployment repo
      uses: actions/checkout@v3
      with:
        repository: hypothesis/dummy-deploy
        ssh-key: ${{ secrets.DEPLOYMENT_KEY }}
    - name: install boto3
      run: pip install boto3
    - name: Run production deployment (us-west-1)
      run: |
        export APP="dummy-h-periodic" TYPE="deploy" ENV="prod" REGION="us-west-1" APP_DOCKER_VERSION="latest"
        ./bin/jenkins

  deploy-prod-ca-central-1:
    name: Prod - CA-Central-1
    needs: deploy-qa
    runs-on: ubuntu-latest
    environment: Production
    if: github.ref == 'refs/heads/main'
    steps:
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::964867326460:role/Deployments
        role-duration-seconds: 900
        aws-region: us-west-1
    - name: Checkout deployment repo
      uses: actions/checkout@v3
      with:
        repository: hypothesis/dummy-deploy
        ssh-key: ${{ secrets.DEPLOYMENT_KEY }}
    - name: install boto3
      run: pip install boto3
    - name: Run production deployment (ca-central-1)
      run: |
        export APP="dummy-h-periodic-ca" TYPE="deploy" ENV="prod" REGION="ca-central-1" APP_DOCKER_VERSION="latest"
        ./bin/jenkins
