name: Release

concurrency: dummy-h-periodic-release

on:
  push:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build-test-release:
    name: Build, Test & Release
    runs-on: ubuntu-latest
    env:
      name: dummy-h-periodic
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        GIT_SHORT=$(git rev-parse --short HEAD)
        GIT_COMMIT_TIMESTAMP=$(git --no-pager show -s --format=%ct $GIT_SHORT)
        GIT_TS_CONVERTED=$(date -d @$GIT_COMMIT_TIMESTAMP +"%Y%m%d")
        VERSION=$(echo "$GIT_TS_CONVERTED-g$GIT_SHORT")
        export TAG=${VERSION//+/-}
        echo "::set-env name=TAG::$TAG"
        git archive HEAD | docker build -t "hypothesis/${name}:${TAG}" -
    - name: Test
      run: |
        echo "Add tests here!"
    - name: Release
      if: github.ref == 'refs/heads/master'
      run: |
        echo "${{ secrets.DOCKER_KEY }}" | docker login -u indigobravo  --password-stdin
        docker push "hypothesis/${name}:${TAG}"
        docker tag "hypothesis/${name}:${TAG}" "hypothesis/${name}:latest"
        docker push "hypothesis/${name}:latest"

  deploy-qa:
    name: Deploy QA
    needs: build-test-release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Dummy Deploy QA
      run: echo "Master branch - Deploy QA"

  deploy-prod:
    name: Deploy Prod
    needs: deploy-qa
    runs-on: ubuntu-latest
    environment: Production
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Dummy Deploy Prod
      run: echo "Master branch - Deploy prod"
