name: Synchronize AWS Environment

concurrency: dummy-h-periodic-sync-env

on:
  workflow_dispatch:
    inputs: 
      Environment:
        description: "The environment to synchronize. Can be either: 'qa', 'prod', or 'all'."
        required: true
        default: 'qa'
      Region:
        description: "The AWS region to target. Can be either: 'us-west-1', 'ca-central-1', or 'all'."
        required: true
        default: 'us-west-1'

permissions:
  id-token: write # required to use AWS OIDC auth

env:
  APP: 'dummy-h-periodic'
  TYPE: 'sync-env'
  ENV: ${{ github.event.inputs.Environment }}
  REGION: ${{ github.event.inputs.Region }}
  APP_DOCKER_VERSION: ${{ github.event.inputs.Version }}
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  sync-env:
    runs-on: ubuntu-latest
    steps:
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/Deployments
        role-duration-seconds: 900
        aws-region: us-west-1
    - name: Checkout deployment Repo
      uses: actions/checkout@v3
      with:
        repository: hypothesis/dummy-deploy
        ssh-key: ${{ secrets.DEPLOYMENT_KEY }}
    - name: install boto3
      run: pip install boto3
    - name: Synchronize AWS Environment
      run: |
        ./bin/jenkins
