name: Sync Environment

# Sync Elastic Beanstalk environment definitions with a live service.
#
# Environment definitions can be found here:
# - https://github.com/hypothesis/deployment

on:
  workflow_dispatch:
    inputs: 
      Environment:
        type: choice
        description: "The environment to deploy. Can be either: 'qa' or 'prod'."
        required: true
        default: 'qa'
        options:
          - qa
          - prod
      Region:
        type: choice
        description: "The AWS region to target. Can be either: 'us-west-1', or 'ca-central-1', or 'all'."
        required: true
        default: 'all'
        options:
          - us-west-1
          - ca-central-1
          - all

permissions:
  id-token: write # required to use AWS OIDC auth

env:
  APP: 'dummy-h-periodic'
  TYPE: 'sync-env'
  ENV: ${{ github.event.inputs.Environment }}
  REGION: ${{ github.event.inputs.Region }}

jobs:
  sync-env:
    runs-on: ubuntu-latest
    steps:
    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.DEPLOYMENT_AWS_ROLE_ARN }}
        role-duration-seconds: 900
        aws-region: us-west-1
    - name: Checkout deployment repo
      uses: actions/checkout@v3
      with:
        repository: ${{ secrets.DEPLOYMENT_REPOSITORY }}
        ssh-key: ${{ secrets.DEPLOYMENT_REPOSITORY_KEY }}
    - name: Prepare environment
      run: pip install boto3 pyaml
    - name: Synchronize AWS Environment
      run: |
        ./bin/init.sh
